### PR TITLE
Update lasercut.scad

### PR DESCRIPTION
**Pull request by The009**
Fix the finger joints to not extend into the model.

### CODE REVIEW

**Comment by The009** [comment]
pull39

**Comment by bmsleight** [comment]
Just back from holiday .... will look as soon. Thanks.

**Comment by bmsleight** [comment]
I would like the openscad command used to for the image attached, so can understand better the bug.
Thanks for the help.

**Comment by The009** [comment]
> I would like the openscad command used to for the image attached, so can understand better the bug. Thanks for the help.

`include <lasercut.scad>; 

thickness = 19.05;
length = 101.6;
width = 101.6;

module platform(){
lasercutoutSquare(thickness, length, width,
    finger_joints=[
            [UP, 1, 4],
            [DOWN, 0, 4],
            [LEFT, 0,4],
        ]
    );
};



module sideWall(){
    points = [[0,0], [length,0], [length,0], [0,length], [length,length/2], [0,length], [0,0]];
    color("BLUE",0.75)
    lasercutout(thickness, points,
        finger_joints=[
            [DOWN, 0, 4],
            [LEFT, 0,4],
        ],
        //Add a simple tab to cover the back corner and add a very little bit to remove the line generaged in svg (BUG?)
        simple_tabs=[[DOWN, -thickness/2 +.00001, 0]]
    );
};

platform();

translate([0,0,0]) rotate([90,90,0]) sideWall();
translate([0,width+thickness,0]) rotate([90,90,0]) sideWall();`

**Comment by bmsleight** [comment]
Sorry took me a while! Thanks.

**Pull request merged**
